/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_untaek_animal_NativeAdapter */

#ifndef _Included_io_untaek_animal_NativeAdapter
#define _Included_io_untaek_animal_NativeAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_untaek_animal_NativeAdapter
 * Method:    hello
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_untaek_animal_NativeAdapter_hello
  (JNIEnv *, jobject);

/*
 * Class:     io_untaek_animal_NativeAdapter
 * Method:    helloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_untaek_animal_NativeAdapter_helloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
